### ISSUE TITLE
Send flag if the user has completed KYC in /login

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#157]
Send flag if the user has completed KYC/Registered for Rapyd Wallet  in /login response.

**Comment by beniaminmunteanu** [comment]
In case you want to already develop the FE side, the mentioned flag will be a boolean "noKYC". It will only appear in the login response if the KYC is not completed, othwerwise it will not be returned.

**Comment by raducristianpopa** [comment]
I don't think the KYC flag should be sent in the login response. Imagine this case:
- user logs in
- gets redirected to KYC page
- closes the browser
- opens the browser and goes to homepage

We will not be able to tell if the user completed KYC or not. Receiving this information when we check if the user is authenticated (on FE side) would be more reliable since it will eliminate the case above (for ie: an endpoint <`/me`> that will respond with the user info along with the KYC flag).

**Comment by beniaminmunteanu** [comment]
The current implementation is as such:

- Upon login, the backend encodes "noKYC" in the access token of a user without KYC.
- Any request of a such user will be blocked with Unauthorised, if it is not targeted to /wallet (which would be the endpoint for actually providing the KYC and creating the wallet)

- Additionally, as per our FE application needs, a new /me endpoint is created, which returns the user profile. (Along with the no-kyc information) -> NextJS will hit this endpoint before rendering pages, to check it's authenticated state. 
It is at this point in which it will also see if the KYC is provided or not. If it is not, the user will be redirected accrodingly
