### ISSUE TITLE
[BUG] Boutique mobile fix

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1818]
### Steps to reproduce

1. Go to Boutique checkout mobile and the buttons are overlapping

### Expected result

Buttons wrao nicely

### Actual result

Buttons are overlapping

### Operating system

Windows

### Browsers

Chrome

**Comment by lattaai9** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the checkout page layout to improve responsiveness on mobile devices. Adjusted the grid layout and added responsive classes to ensure buttons wrap properly on smaller screens.

You can review changes in this commit: https://github.com/lattaai9/interledger-testnet-1818/commit/ed0487953406a48c4752629bdbdea6908b1c58b7.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Tymmmy** [comment]
Hello @lattaai9 , thank you for solving this, we actually needed it quick yesterday for a hotfix, and we already deployed it asap. If you check the timeline, you can see the story was created, assigned and quickly solved and merged :) . We are looking forward to you contributing in further Interledger stories.
