### ISSUE TITLE
Investigate transaction delays

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#501]
While sending money, the transaction of the sender is complete almost instantly, but the receiver has Pending for a longer time.
We should investigate if we can reduce the time that the transaction stays on Pending and becomes Completed.

**Comment by raducristianpopa** [comment]
One _possible reason_ we might experience some transaction delays is that we set an expiry (2 minutes) for created incoming payments when making a payment directly to a payment pointer.

https://github.com/interledger/testnet/blob/3529d3a6f25180b9075216f83bd2be91dba91148/packages/wallet/backend/src/quote/service.ts#L112-L123

The reason for doing this is that in a `FixedSend` + payment pointer scenario, the incoming payment is created with no `incomingAmount` since we do not know how much liquidity the receiver should get. One option could be to manually complete the incoming payment, but we do know when this specific incoming payment is completed. Therefor, currently we wait for the `incoming_payment.expired` webhook and then mark the incoming payment as completed.
