### ISSUE TITLE
Create release for deployment

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/testnet#578]
Rather than having a PR that requires merging into the `release` branch to deploy, we can choose to use GitHub releases. With this approach, whenever a release is created for the `main` branch, it will automatically trigger the deployment workflow.

Rafiki already has this model implemented, we should do the same.

**Comment by rico191013** [comment]
According to the Rafiki Project, tags and releases are currently created manually. Changes are deployed after each commit push, and for tag creation, the process involves building a Docker container and pushing it to the registry (as opposed to just building a Docker container for commit pushes). 
In our case, should we modify the `ci_deploy.yml` file to initiate the deployment process upon tag creation instead of pushing to the release branch?
